# Generated by Django 4.0.4 on 2022-11-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='pokedex_app.pokemontype'),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
